pub const MAX_EOCD_SEARCH_BYTES: u64 = 65_558;
pub const CONCURRENT_REQUESTS: usize = 50;
pub const DOWNLOAD_TIMEOUT_SECS: u64 = 60;
pub const DEFAULT_PROGRESS_WATCHDOG_SECS: u64 = 120;
pub const COLLECTION_FETCH_TIMEOUT_SECS: u64 = 30;
